openapi: 3.0.1
info:
  title: Counseling Tools Service
  description: 'Spec for counselingToolsService'
  version: 0.2.0

paths:
  /api/public/v1/queries/query_datasource_plus_e6abf1178d86401d83b589a6c9dd80d1_4304f849f9ba46aa8009921e2c8dfc12:
    post:
      summary: Get all available consulting apps
      operationId: getApps
      parameters:
        - name: x-budibase-app-id
          in: header
          description: Budibase App ID
          schema:
            type: string
          required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppsQueryResponse'
      security:
        - ApiKeyAuth: [ ]
  /api/public/v1/users/:
    get:
      tags:
        - consultant
      summary: Get budibase user
      operationId: getUser
      parameters:
        - name: budibaseUserId
          in: path
          description: ID of budibase user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - ApiKeyAuth: [ ]

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-budibase-api-key
  schemas:
    AppsQueryResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int32
              budibase_id:
                type: string
              url:
                type: string
              Title:
                type: string
              Description:
                type: string
              Enabled:
                type: integer
                format: int32
    User:
      type: object
      properties:
        data:
          type: object
          properties:
            _id:
              type: string
            email:
              type: string
            status:
              type: string
            firstName:
              type: string
            lastName:
              type: string
            forceResetPassword:
              type: boolean
            roles:
              type: object