openapi: 3.0.1
info:
  title: Counseling Tools Service
  description: 'Spec for counselingToolsService'
  version: 0.2.0

paths:
  /api/public/v1/queries/{queryId}:
    post:
      summary: Get all available consulting apps
      operationId: executeBudibaseQuery
      parameters:
        - name: queryId
          in: path
          description: Query ID
          schema:
            type: string
          required: true
        - name: x-budibase-app-id
          in: header
          description: Budibase App ID
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
      security:
        - ApiKeyAuth: [ ]
  /api/public/v1/users/{budibaseUserId}:
    get:
      summary: Get budibase user
      operationId: getUser
      parameters:
        - name: budibaseUserId
          in: path
          description: ID of budibase user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - ApiKeyAuth: [ ]
    put:
      summary: Assign tools to advice seeker
      operationId: assignTools
      parameters:
        - name: budibaseUserId
          in: path
          description: ID of budibase user
          required: true
          schema:
            type: string
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/AssignToolsRequest'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-budibase-api-key
  schemas:
    App:
      type: object
      properties:
        id:
          type: integer
          format: int32
        budibaseId:
          type: string
        url:
          type: string
        title:
          type: string
        description:
          type: string
        type:
          type: string
    AssignToolsRequest:
      type: object
      properties:
        status:
          type: string
        roles:
          type: object
          additionalProperties: true
    User:
      type: object
      properties:
        data:
          type: object
          properties:
            _id:
              type: string
            email:
              type: string
            status:
              type: string
            firstName:
              type: string
            lastName:
              type: string
            forceResetPassword:
              type: boolean
            roles:
              type: object
    ConsultantAssignedUsers:
      type: object
      properties:
        data:
          type: object
        extra:
          type: object
