openapi: 3.0.1
info:
  title: Counseling Tools Service
  description: 'Spec for counselingToolsService'
  version: 0.1.0

paths:
  /tools/{adviceSeekerId}:
    get:
      tags:
        - budibase-controller
      summary: Get a list of all assigned tools for given advice seeker
      operationId: getAdviceSeekerAssignedTools
      parameters:
        - name: adviceSeekerId
          in: path
          description: BudiBase ID of advice seeker
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolsListResponse'
      security:
        - Bearer: []
    put:
      summary: Assign tools to advice seeker
      operationId: assignTools
      parameters:
        - name: adviceSeekerId
          in: path
          description: ID of budibase user
          required: true
          schema:
            type: string
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/AssignToolsRequest'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolsListResponse'
components:
  schemas:
    ToolsListResponse:
      type: array
      items:
        $ref: '#/components/schemas/Tool'
    Tool:
      type: object
      properties:
        toolId:
          type: string
        url:
          type: string
        title:
          type: string
        description:
          type: string
        sharedWithAdviceSeeker:
          type: boolean
        sharedWithConsultant:
          type: boolean
    AssignToolsRequest:
      type: array
      items:
        type: string
