openapi: 3.0.1
info:
  title: Counseling Tools Service
  description: 'Spec for counselingToolsService'
  version: 0.1.0

paths:
  /apps:
    get:
      summary: Get all available consulting apps
      operationId: getApps
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfApps'
      security:
        - Bearer: []

components:
  schemas:
    ArrayOfApps:
      type: array
      items:
        $ref: './../services/budibaseApi.yaml#/components/schemas/App'